name: Build

on: [push]

env:
  BUILD_CONFIGURATION: Debug

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@master
        with:
          version: "18.1.8"

      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@main
        with:
          vulkan-query-version: 1.4.304.1
          vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang, SPIRV-Tools
          vulkan-use-cache: true

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: CMake Generate
        run: cmake --preset release

      - name: Build
        run: cmake --build --preset release

  build-linux:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake clang lld libx11-dev libxi-dev libgl1-mesa-dev libvulkan-dev libxinerama-dev libxcursor-dev

      - name: Setup Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@main
        with:
          vulkan-query-version: 1.4.304.1
          vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang, SPIRV-Tools
          vulkan-use-cache: true

      - name: CMake Generate
        run: cmake --preset release

      - name: Build
        run: cmake --build --preset release
