name: Build

on: [push]

env:
  BUILD_CONFIGURATION: Debug

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "17.0"

      # Cache vcpkg installed dependencies
      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: |
            C:/Users/runneradmin/.cache/vcpkg
            C:/vcpkg/installed
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-

      - name: Restore artifacts, or setup vcpkg for building artifacts
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          vcpkgJsonGlob: "./vcpkg.json"
          runVcpkgInstall: true

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      # Cache CMake build directory
      - name: Cache CMake build artifacts
        uses: actions/cache@v4
        with:
          path: |
            build/
          key: cmake-build-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            cmake-build-${{ runner.os }}-

      - name: CMake Generate
        run: cmake --preset release

      - name: Build
        working-directory: ${{github.workspace}}
        run: cmake --build --preset release
