name: Build

on: [push]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Debug

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "16.0"
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
        
    - name: Prepare Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: 1.3.261.1
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config
        version: 1.0

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "16.0"

    - name: List $RUNNER_WORKSPACE before build
      run: find $RUNNER_WORKSPACE
      shell: bash

    - name: Restore artifacts, or setup vcpkg for building artifacts
      uses: lukka/run-vcpkg@v10
      id: runvcpkg
      with:
        vcpkgJsonGlob: './vcpkg.json'
        runVcpkgInstall: true

    - name: CMake Generate
      run: cmake -B build -S . -G "Unix Makefiles"
      env:
        CC: '/home/runner/work/triton/triton/llvm/bin/clang'
        CXX: '/home/runner/work/triton/triton/llvm/bin/clang++'
 
    - name: Build
      working-directory: ${{github.workspace}}
      run: cmake --build build --target=driver -j 18
