name: Build

on: [push]

env:
  BUILD_CONFIGURATION: Debug

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@main
        with:
          vulkan-query-version: 1.4.304.1
          vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang, SPIRV-Tools
          vulkan-use-cache: true

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: CMake Generate
        run: cmake --preset msvc-debug

      - name: Build
        run: cmake --build --preset msvc-debug

  build-linux:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build lld libx11-dev libxi-dev libgl1-mesa-dev libvulkan-dev libxinerama-dev libxcursor-dev wget gnupg lsb-release software-properties-common libstdc++-13-dev

      - name: Add LLVM apt repository
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/llvm.asc
          echo "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-20 main" | sudo tee /etc/apt/sources.list.d/llvm20.list

      - name: Install LLVM 20
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-20 lldb-20 lld-20 llvm-20

      - name: Set LLVM 20 as default
        run: |
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-20 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-20 100
          clang --version

      - name: Setup Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@main
        with:
          vulkan-query-version: 1.4.304.1
          vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang, SPIRV-Tools
          vulkan-use-cache: true

      - name: Configure build with Clang 20 and libstdc++ 15
        run: cmake --preset release

      - name: Build
        run: cmake --build --preset release --target Cauldron
